### ISSUE TITLE
Supportting for ZRWA

### ISSUE THREAD

**Issue by huqianshan** [westerndigitalcorporation/libzbd#25]
Currently, the NVMe standard is under consideration to include the **Zone Random Write Area (ZRWA).** 
However, in its current state, `libzbd` is unable to specify the **ZRWA** open flag through the `zbd_open_zones()` function, and also lacks the **explicit flush** interface. 
As **ZRWA** is expected to become a standard in the future,  it's interesting to know if `libzbd` plans to implement this feature to align with the upcoming NVMe standard. 

`libzbd` helps me a lot to use ZNS， good work ：）

**Comment by damien-lemoal** [comment]
ZRWA is already approved by NVM Express as TP4076b. Regarding supporting ZRWA in libzbd, I am afraid this is not possible since the kernel does not support this TP. libzbd relies solely on the kernel zoned block user API (/usr/include/linux/blkzoned.h) for its implementation and this API does not have ZRWA support. If you want to use ZRWA, you may want to look at a passthrough library like libnvme (used in the nvme cli tool).

**Comment by huqianshan** [comment]
> ZRWA is already approved by NVM Express as TP4076b. Regarding supporting ZRWA in libzbd, I am afraid this is not possible since the kernel does not support this TP. libzbd relies solely on the kernel zoned block user API (/usr/include/linux/blkzoned.h) for its implementation and this API does not have ZRWA support. If you want to use ZRWA, you may want to look at a passthrough library like libnvme (used in the nvme cli tool).

Ok. Thanks for your reply.
